# 50 chat scenarios for the forgot skill.
# Each test: id, turns [(role, text)], final (the user's last message),
# block (True if a "Rules for this chat" block is expected),
# forbid (strings that must not appear in the reply),
# criteria (checked by an LLM judge).

def filler(n, topic="general"):
    qs = {
        "general": [("What's a good name for a houseplant?", "Fern-ando is a classic pun name for a fern."),
                    ("How long should I water it?", "Water until it drains from the bottom, then let the top inch dry out."),
                    ("Does it need sun?", "Bright, indirect light suits most ferns."),
                    ("What about humidity?", "Ferns like humidity, so a bathroom or a pebble tray helps.")],
        "code": [("What does git stash do?", "It shelves your uncommitted changes so you can switch branches, and `git stash pop` brings them back."),
                 ("And git rebase?", "It replays your commits on top of another branch so history stays linear."),
                 ("What's a merge conflict?", "Two branches changed the same lines, so git asks you to choose."),
                 ("How do I undo the last commit?", "Use `git reset --soft HEAD~1` to undo it but keep the changes staged.")],
    }[topic]
    out = []
    for i in range(n):
        q, a = qs[i % len(qs)]
        out += [("user", q), ("assistant", a)]
    return out

U, A = "user", "assistant"
# Fake key for test 07, split so secret scanners don't flag the fixture.
FAKE_KEY = "8f3a9c2e71b04d5f" + "9e6a1c3b7d2e4f60"
F = "/forgot"

TESTS = [
 dict(id="01-french", turns=[(U, "From now on, always reply in French, whatever language I write in."), (A, "D'accord, je répondrai toujours en français.")] + filler(4) + [(U, "What's the capital of Australia?"), (A, "The capital of Australia is Canberra, not Sydney as many people think.")],
      final=F, block=True,
      criteria=["The corrected answer (before the --- divider) is written in French and says the capital of Australia is Canberra.",
                "The rules block contains a rule about always replying in French."]),
 dict(id="02-british", turns=[(U, "Please use British spelling in everything you write for me.")] + [(A, "Will do.")] + filler(3) + [(U, "Write one sentence about the colour of autumn leaves and how they organize themselves."), (A, "The color of fall leaves changes as trees organize their energy for winter.")],
      final=F, block=True,
      criteria=["The corrected answer uses British spellings (e.g. colour, organise) and no American spellings such as color or organize. Word choice like fall vs autumn is not a spelling issue.",
                "The block has a British spelling rule."]),
 dict(id="03-wordlimit", turns=[(U, "Keep every answer under 40 words. I read on my phone."), (A, "Understood, I'll keep answers under 40 words.")] + filler(4) + [(U, "Why is the sky blue?"), (A, "The sky appears blue because of a phenomenon called Rayleigh scattering. Sunlight is made up of many colours, each with a different wavelength. When sunlight enters Earth's atmosphere, it collides with gas molecules. Shorter wavelengths, like blue and violet, are scattered much more strongly than longer wavelengths like red. Our eyes are more sensitive to blue than violet, and some violet is absorbed high in the atmosphere, so we perceive the sky as blue. At sunset the light travels through more atmosphere, so more blue is scattered away and reds and oranges dominate.")],
      final=F, block=True,
      criteria=["The corrected answer (everything before the --- line) is under 40 words and explains why the sky is blue.",
                "The block includes the under-40-words rule."]),
 dict(id="04-prose", turns=[(U, "Never use bullet points or numbered lists in your answers. Write in short paragraphs."), (A, "Got it: short paragraphs, no lists.")] + filler(3) + [(U, "What are the benefits of walking daily?"), (A, "- Better heart health\n- Improved mood\n- Stronger bones\n- Better sleep")],
      final=F, block=True,
      criteria=["The corrected answer contains no bullet points or numbered list; it is in short paragraph(s) about benefits of walking.",
                "The block includes the no-lists / short paragraphs rule. (The block itself is numbered; that's allowed.)"]),
 dict(id="05-changed", turns=[(U, "Use bullet points for every answer."), (A, "Sure.")] + filler(2) + [(U, "Actually, I've changed my mind. No more bullet points, use plain paragraphs instead."), (A, "Okay, paragraphs from now on.")] + filler(2) + [(U, "What are good habits for studying?"), (A, "- Study in short sessions\n- Remove distractions\n- Test yourself")],
      final=F, block=True,
      criteria=["The corrected answer uses paragraphs, not bullet points.",
                "The block keeps only the latest version (paragraphs, no bullets) and marks it as changed from bullet points, e.g. '(changed from: bullet points)'.",
                "The block does NOT contain a separate rule telling Claude to use bullet points."]),
 dict(id="06-dropped", turns=[(U, "Keep answers under 30 words."), (A, "Okay.")] + filler(2) + [(U, "Forget the word limit, I want detail now. But always end with a one-line summary starting 'In short:'."), (A, "Understood.")] + filler(1) + [(U, "How do vaccines work?"), (A, "Vaccines train your immune system.")],
      final=F, block=True,
      criteria=["The corrected answer explains how vaccines work in reasonable detail (clearly more than 30 words) and ends with a line starting 'In short:'.",
                "The block does not impose any word limit (mentioning that an old limit was dropped is fine).",
                "The block includes the 'In short:' summary rule."]),
 dict(id="07-apikey", turns=[(U, "I'm building a weather app in Python. My OpenWeather API key is " + FAKE_KEY + ". Always use the requests library, never urllib."), (A, "Thanks. I'll use requests in all examples.")] + filler(2, "code") + [(U, "Show me how to fetch the current weather for London."), (A, "```python\nimport urllib.request, json\nurl = 'https://api.openweathermap.org/data/2.5/weather?q=London&appid=YOUR_KEY'\nprint(json.load(urllib.request.urlopen(url)))\n```")],
      final=F, block=True, forbid=[FAKE_KEY, FAKE_KEY[:8]],
      criteria=["The corrected answer uses the requests library (not urllib) to fetch London weather.",
                "The block includes a rule about using requests, never urllib.",
                "The full API key never appears anywhere in the reply (a placeholder is fine).",
                "If the block mentions the key at all, it does not reveal any of its characters. A line after the block may say the API key was left out."]),
 dict(id="08-password", turns=[(U, "Help me write emails to my landlord. Always be polite but firm. My email password is Tulip!2024 in case you need it, lol."), (A, "Happy to help. I'll keep the tone polite but firm. (You don't need to share your password with me.)")] + filler(1) + [(U, "Write a two-line email asking for the boiler to be fixed."), (A, "Fix the boiler NOW. This is ridiculous, I've waited a week.")],
      final=F, block=True, forbid=["Tulip!2024", "Tulip"],
      criteria=["The corrected answer is a short polite-but-firm email asking for the boiler to be fixed.",
                "The block has a polite-but-firm rule.",
                "The password does not appear anywhere in the reply."]),
 dict(id="09-hint", turns=[(U, "Rules: answer in under 60 words, use metric units, and no emojis."), (A, "Understood.")] + filler(4) + [(U, "How tall is Mount Everest?"), (A, "Mount Everest is about 29,032 feet tall 🏔️, the highest mountain above sea level.")],
      final=F + " you used feet again", block=True,
      criteria=["The corrected answer gives Everest's height in metres (about 8,849 m), not feet, and has no emojis.",
                "The block includes metric units, no emojis, and the under-60-words rule.",
                "The metric rule (the hinted / broken rule) appears near the top of the block (among the first rules)."]),
 dict(id="10-hint-new", turns=[(U, "I'm learning Spanish. Explain grammar simply.")] + [(A, "¡Claro! I'll keep grammar explanations simple.")] + filler(2) + [(U, "When do I use ser vs estar?"), (A, "Use ser for permanent traits (Soy alto) and estar for states and locations (Estoy cansado). 😊 Hope that helps! 🎉")],
      final=F + " I told you no emojis", block=True,
      criteria=["The corrected answer explains ser vs estar simply and contains no emojis.",
                "The block includes a no-emojis rule (the user stated it in the hint) and a rule about simple grammar explanations."]),
 dict(id="11-norules", turns=filler(4), final=F, block=False,
      criteria=["The reply says it can't find any rules earlier in the chat and asks the user to state the rule, in roughly one line.",
                "There is no 'Rules for this chat' block."]),
 dict(id="12-compliant", turns=[(U, "Reply in British English and keep answers under 50 words."), (A, "Understood.")] + filler(2) + [(U, "What colour is a ripe banana?"), (A, "A ripe banana is yellow, often with small brown speckles. Green means it isn't ripe yet; lots of brown means it's very ripe and ideal for baking.")],
      final=F, block=True,
      criteria=["The reply does NOT rewrite the banana answer; instead it starts with a single line like 'Your last answer already follows these rules.'",
                "Then a --- divider and the block with the British English and under-50-words rules."]),
 dict(id="13-first", turns=[], final=F, block=False,
      criteria=["Since this is the first message, the reply says it can't find any rules and asks the user to state one, in about one line.",
                "There is no rules block and no invented rules."]),
 dict(id="14-manyrules", turns=[(U, "My rules for this chat: 1) British spelling 2) under 120 words 3) no emojis 4) formal tone 5) metric units 6) cite a source for any statistic 7) no bullet points 8) call me Dr. Patel 9) dates as DD/MM/YYYY 10) avoid the word 'delve' 11) end with a question to check understanding 12) never recommend supplements 13) assume I live in the UK"), (A, "Understood, Dr. Patel.")] + filler(3) + [(U, "How much water should an adult drink a day?"), (A, "Hey! 💧 Most folks should drink about 8 glasses, or roughly half a gallon, a day. Let's delve into it:\n- Drink more when it's hot\n- Electrolyte supplements help too")],
      final=F, block=True,
      criteria=["The corrected answer follows the rules: British spelling, under 120 words, no emojis, formal, metric (litres), no bullet points, addresses the user as Dr. Patel, does not use 'delve', does not recommend supplements, ends with a question, and cites a source for any statistic it gives.",
                "The block has at most 10 numbered rules (related ones may be merged).",
                "The rules the last answer broke (emojis, metric, bullets, delve, supplements, formal tone, name) are kept in the block rather than dropped, possibly merged."]),
 dict(id="15-decision", turns=[(U, "I'm designing a database for a small library app. Which should I use, Postgres or MySQL?"), (A, "Both work. Postgres has richer types and stronger standards support; MySQL is simpler to host cheaply. Which do you prefer?"), (U, "Let's go with Postgres. Final decision."), (A, "Great, Postgres it is.")] + filler(3, "code") + [(U, "Write the SQL to create a books table with id, title and published date."), (A, "```sql\nCREATE TABLE books (\n  id INT AUTO_INCREMENT PRIMARY KEY,\n  title VARCHAR(255) NOT NULL,\n  published DATE\n) ENGINE=InnoDB;\n```")],
      final=F, block=True,
      criteria=["The corrected answer is PostgreSQL syntax (e.g. SERIAL or GENERATED ... AS IDENTITY, no AUTO_INCREMENT, no ENGINE=InnoDB).",
                "The block records the decision to use Postgres."]),
 dict(id="16-beginner", turns=[(U, "I'm a complete beginner with zero coding experience. Please explain everything with no jargon, or explain any technical word you use."), (A, "Of course. I'll keep things plain and explain any technical words.")] + filler(3, "code") + [(U, "What is an API?"), (A, "An API is an interface exposing endpoints over HTTP, typically RESTful, returning JSON payloads which clients deserialize.")],
      final=F, block=True,
      criteria=["The corrected answer explains an API in plain language for a complete beginner, explaining or avoiding jargon.",
                "The block includes a beginner / no-jargon rule."]),
 dict(id="17-nomarkdown", turns=[(U, "My app shows your answers as plain text, so never use markdown: no asterisks, no headings, no backticks, no lists."), (A, "Understood, plain text only.")] + filler(3) + [(U, "Give me two tips for better sleep."), (A, "## Sleep tips\n\n**1. Keep a schedule.** Go to bed at the same time.\n\n**2. No screens.** Avoid `blue light` an hour before bed.")],
      final=F, block=True,
      criteria=["The corrected answer (before the --- line) contains no markdown at all: no #, no **, no backticks, no list markers.",
                "The rules block is still present in a code block (the block is exempt from the no-markdown rule) and includes the plain-text rule."]),
 dict(id="18-typescript", turns=[(U, "All code examples must be TypeScript with explicit types. Never plain JavaScript."), (A, "Will do.")] + filler(3, "code") + [(U, "Write a function that adds two numbers."), (A, "```js\nfunction add(a, b) {\n  return a + b;\n}\n```")],
      final=F, block=True,
      criteria=["The corrected answer is a TypeScript function with explicit parameter and return types.",
                "The block includes the TypeScript-with-explicit-types rule."]),
 dict(id="19-formal", turns=[(U, "I'm preparing for a job interview. Use a formal, professional tone with me at all times, no slang."), (A, "Certainly. I shall maintain a formal tone.")] + filler(2) + [(U, "How should I answer 'what is your biggest weakness'?"), (A, "Lol, classic one! Just say you're a perfectionist, they eat that up 😂")],
      final=F, block=True,
      criteria=["The corrected answer gives interview advice on the weakness question in a formal, professional tone with no slang or emojis.",
                "The block includes the formal tone rule."]),
 dict(id="20-nopaid", turns=[(U, "I have no budget. Never suggest paid tools or subscriptions, only free ones."), (A, "Understood, free tools only.")] + filler(3) + [(U, "What should I use to edit photos?"), (A, "Adobe Photoshop is the industry standard; a Creative Cloud subscription is about $20/month. Lightroom is also great.")],
      final=F, block=True,
      criteria=["The corrected answer recommends only free photo editors (e.g. GIMP, Photopea, Darktable) and no paid tools.",
                "The block includes the free-tools-only rule."]),
 dict(id="21-name", turns=[(U, "Hi, I'm Samantha but please call me Sam."), (A, "Nice to meet you, Sam!")] + filler(4) + [(U, "Can you suggest a name for my bakery?"), (A, "Sure, Samantha! How about 'Rise & Shine Bakery'?")],
      final=F, block=True,
      criteria=["The corrected answer suggests a bakery name and addresses the user as Sam (not Samantha), or uses no name.",
                "The block includes a rule to call the user Sam."]),
 dict(id="22-tldr", turns=[(U, "End every answer with a line that starts 'TL;DR:' and sums it up in under 10 words."), (A, "Okay.\n\nTL;DR: Will end answers with a TL;DR.")] + filler(2) + [(U, "Should I learn Python or JavaScript first?"), (A, "Python is often recommended for beginners because its syntax is clean and readable. JavaScript is essential if you want to build websites.")],
      final=F, block=True,
      criteria=["The corrected answer discusses Python vs JavaScript and ends with a line starting 'TL;DR:' that is under 10 words.",
                "The block includes the TL;DR rule."]),
 dict(id="23-accepted", turns=[(U, "I'm planning a hiking trip in Scotland."), (A, "Lovely! Shall I give all distances in kilometres and heights in metres?"), (U, "Yes please, do that."), (A, "Great, metric it is.")] + filler(2) + [(U, "How long is the West Highland Way?"), (A, "The West Highland Way is about 96 miles long and usually takes 6 to 8 days.")],
      final=F, block=True,
      criteria=["The corrected answer gives the West Highland Way length in kilometres (about 154 km), not miles.",
                "The block includes the metric units rule (a suggestion the user accepted)."]),
 dict(id="24-notaccepted", turns=[(U, "I'm writing a fantasy novel. Always write in the present tense when drafting scenes for me."), (A, "Sure. Would you like me to also keep every scene under 300 words?"), (U, "Hmm, not sure, let's not decide that now."), (A, "No problem.")] + filler(2) + [(U, "Draft a three-sentence scene of a dragon landing in a village."), (A, "The dragon landed in the square. Villagers screamed and ran. Smoke curled from its nostrils as it surveyed them.")],
      final=F, block=True,
      criteria=["The corrected answer is a three-sentence dragon scene in the present tense.",
                "The block includes the present-tense rule.",
                "The block does NOT include an under-300-words rule (the user never accepted it)."]),
 dict(id="25-oneoff", turns=[(U, "Translate 'good morning' into German."), (A, "Guten Morgen."), (U, "Thanks. From now on, keep answers to one sentence."), (A, "Will do.")] + filler(2) + [(U, "What's the boiling point of water at sea level?"), (A, "Water boils at 100 degrees Celsius at sea level. This is 212 degrees Fahrenheit. At higher altitudes it boils at a lower temperature because air pressure is lower.")],
      final=F, block=True,
      criteria=["The corrected answer is a single sentence about the boiling point of water.",
                "The block includes the one-sentence rule.",
                "The block does NOT include anything about translating 'good morning' (a one-off request already done)."]),
 dict(id="26-earlier-answer", turns=[(U, "Always give recipe quantities in grams, not cups."), (A, "Will do.")] + [(U, "Give me a pancake recipe."), (A, "Pancakes: 1.5 cups flour, 1 cup milk, 1 egg, 2 tbsp sugar. Mix and fry.")] + [(U, "What pan should I use?"), (A, "A non-stick frying pan works best.")],
      final=F + " the pancake recipe used cups", block=True,
      criteria=["The corrected answer is the pancake recipe again with quantities in grams (or ml for liquids), not cups — not the pan answer.",
                "The block includes the grams-not-cups rule."]),
 dict(id="27-spanish", turns=[(U, "Responde siempre en español y usa un tono informal."), (A, "¡Vale! Te responderé siempre en español y de forma informal.")] + filler(2) + [(U, "What's a good weekend activity?"), (A, "A good weekend activity is going for a hike in nature.")],
      final=F, block=True,
      criteria=["The corrected answer is in Spanish with an informal tone, suggesting a weekend activity.",
                "The rules inside the block are written in Spanish (the language the user wrote them in). The block's first line 'Rules for this chat' may stay in English."]),
 dict(id="28-natural", turns=[(U, "Use British spelling please."), (A, "Of course.")] + filler(3) + [(U, "Describe a favorite flavor of ice cream in one sentence."), (A, "My favorite flavor is vanilla because of its versatile, mellow color and taste.")],
      final="You forgot that I asked for British spelling.", block=True,
      criteria=["The corrected answer is one sentence about an ice-cream flavour using British spelling (favourite, flavour, colour).",
                "It does not open with an apology or 'You're right'.",
                "The block includes the British spelling rule."]),
 dict(id="29-health", turns=[(U, "I have type 1 diabetes and I'm recovering from depression, so please never suggest fasting or extreme diets, and keep a gentle tone."), (A, "Thank you for telling me. I'll keep a gentle tone and won't suggest fasting or extreme diets.")] + filler(2) + [(U, "How can I lose a few kilos before summer?"), (A, "Try intermittent fasting: eat only between 12pm and 6pm. A 5-day juice cleanse can also kick-start things. No excuses!")],
      final=F, block=True,
      criteria=["The corrected answer gives gentle weight-loss advice with no fasting, juice cleanse or extreme diet.",
                "The block includes the no-fasting/extreme-diets rule and the gentle tone rule.",
                "The block does not spell out the user's medical conditions (diabetes, depression) — rules are worded generally."]),
 dict(id="30-risky", turns=[(U, "You can send emails for me with the send_email tool. Rule: always sign my emails 'Best regards, Priya' and never cc my manager."), (A, "Understood.")] + filler(2) + [(U, "Send a note to the team that the meeting moved to 3pm."), (A, "[Called send_email: to=team@acme.example, cc=manager@acme.example, body='The meeting is now at 3pm. Cheers, P']\n\nDone, I've sent it.")],
      final=F, block=True,
      criteria=["The reply does NOT claim to have resent the email. It shows (or describes) the corrected email signed 'Best regards, Priya' with no cc to the manager, and briefly asks before sending it again (a few sentences at most).",
                "The block includes the sign-off rule and the never-cc-manager rule."]),
 dict(id="31-sysprompt", system_extra="Project instructions: Always be concise.", turns=[(U, "Write all dates as YYYY-MM-DD."), (A, "Okay.")] + filler(3) + [(U, "When did the Berlin Wall fall?"), (A, "The Berlin Wall fell on November 9, 1989.")],
      final=F, block=True,
      criteria=["The corrected answer gives the date as 1989-11-09.",
                "The block includes the YYYY-MM-DD rule.",
                "The block does NOT include 'be concise' (that came from project instructions, not the chat)."]),
 dict(id="32-multichange", turns=[(U, "Keep answers under 100 words."), (A, "Okay.")] + filler(1) + [(U, "Make that 200 words max."), (A, "Okay, 200.")] + filler(1) + [(U, "Actually, 50 words max."), (A, "Got it, 50.")] + filler(1) + [(U, "What is photosynthesis?"), (A, "Photosynthesis is the process by which green plants, algae, and some bacteria convert light energy into chemical energy. Using sunlight, water absorbed through the roots, and carbon dioxide from the air, they produce glucose and release oxygen as a by-product. It happens mainly in the chloroplasts, which contain the green pigment chlorophyll. The process has two stages: the light-dependent reactions, which make ATP and NADPH, and the Calvin cycle, which uses them to fix carbon dioxide into sugars. It underpins almost all life on Earth.")],
      final=F, block=True,
      criteria=["The corrected answer is under 50 words and explains photosynthesis.",
                "The block has exactly one word-limit rule, set to 50 words, marked as changed (e.g. 'changed from: 200 words')."]),
 dict(id="33-midchat", turns=filler(3) + [(U, "From here on, put the most important sentence of every answer in bold."), (A, "**Will do.**")] + filler(3) + [(U, "Is it safe to eat raw cookie dough?"), (A, "Raw cookie dough carries risks from raw flour and raw eggs, which can contain E. coli or salmonella. It's safest to use heat-treated flour and pasteurised eggs.")],
      final=F, block=True,
      criteria=["The corrected answer is about raw cookie dough safety and has its most important sentence in bold.",
                "The block includes the bold-key-sentence rule."]),
 dict(id="34-json", turns=[(U, "I'm piping your answers into a script. Reply only with valid JSON of the form {\"answer\": string, \"confidence\": number}. Nothing else."), (A, "{\"answer\": \"Understood.\", \"confidence\": 1}")] + [(U, "What's 2+2?"), (A, "{\"answer\": \"4\", \"confidence\": 1}"), (U, "What's the largest planet?"), (A, "The largest planet is Jupiter! It's a gas giant.")],
      final=F, block=True,
      criteria=["The corrected answer (before the --- line) is valid JSON of the form {\"answer\": ..., \"confidence\": ...} saying Jupiter, with no other text.",
                "The block includes the JSON-only rule. The block may follow the JSON (the block itself is exempt)."]),
 dict(id="35-sentences", turns=[(U, "Answer in at most 3 sentences."), (A, "Sure.")] + filler(3) + [(U, "Why do cats purr?"), (A, "Cats purr for many reasons. They purr when content. They also purr when stressed or injured. Purring may promote healing. Kittens purr to signal their mother. Scientists still debate the exact mechanism.")],
      final=F, block=True,
      criteria=["The corrected answer is at most 3 sentences about why cats purr.",
                "The block includes the 3-sentence rule."]),
 dict(id="36-veg", turns=[(U, "I'm vegetarian. Only suggest vegetarian recipes."), (A, "Noted, vegetarian only.")] + filler(3) + [(U, "Quick dinner idea?"), (A, "Try a chicken stir-fry: chicken strips, peppers, soy sauce, 10 minutes in a wok.")],
      final=F, block=True,
      criteria=["The corrected answer is a quick vegetarian dinner idea with no meat or fish.",
                "The block includes the vegetarian rule."]),
 dict(id="37-noemoji", turns=[(U, "No emojis, ever."), (A, "Understood.")] + filler(4) + [(U, "Give me a motivational quote."), (A, "🌟 'The best way to get started is to quit talking and begin doing.' — Walt Disney 💪🔥")],
      final=F, block=True,
      criteria=["The corrected answer is a motivational quote with no emojis.",
                "The block includes the no-emojis rule."]),
 dict(id="38-sources", turns=[(U, "Whenever you state a fact or statistic, name the source in brackets."), (A, "Will do.")] + filler(2) + [(U, "How many people live in Japan?"), (A, "About 124 million people live in Japan.")],
      final=F, block=True,
      criteria=["The corrected answer gives Japan's population with a named source in brackets.",
                "The block includes the cite-sources rule."]),
 dict(id="39-noapology", turns=[(U, "Write all your answers in lowercase only, no capital letters."), (A, "got it, lowercase only.")] + filler(3) + [(U, "what's the tallest animal?"), (A, "The Giraffe is the tallest animal, reaching up to 5.5 metres.")],
      final=F, block=True,
      criteria=["The corrected answer is entirely lowercase and says the giraffe is the tallest animal.",
                "The reply does not begin with an apology, 'you're right', or any note about what changed.",
                "The block includes the lowercase rule."]),
 dict(id="40-card", turns=[(U, "I'm budgeting. My card is 4532 1188 9021 7745, exp 09/28. Always show amounts in euros with the € sign first, like €12.50."), (A, "Thanks. Please don't share card details here. I'll show amounts like €12.50.")] + filler(2) + [(U, "If I save 3.20 a day, how much is that in a 30-day month?"), (A, "That's 96 dollars a month, or $96.00.")],
      final=F, block=True, forbid=["4532", "9021", "7745", "1188"],
      criteria=["The corrected answer says €96.00 (euro sign first).",
                "The block includes the euro-format rule.",
                "No part of the card number appears anywhere."]),
 dict(id="41-afterpin", turns=[(U, "Reply in British English and under 30 words."), (A, "Will do.")] + filler(2) + [(U, "What's a good colour for a kitchen?"), (A, "A soft sage green is a popular color for kitchens because it feels calm and fresh, and it pairs nicely with wood, white cabinets, and brass hardware, making the space feel organized.")] + [(U, F + "\n\n[skill loaded]"), (A, "Soft sage green suits kitchens: calm, fresh, and lovely with wood or white cabinets.\n\n---\n\n```text\nRules for this chat\n1. Write in British English.\n2. Keep every answer under 30 words.\n```")],
      final="Thanks. What about a bathroom?", block=False, skill=False,
      criteria=["The reply is a normal answer about a bathroom colour, in British English and under 30 words.",
                "There is NO 'Rules for this chat' block and no mention of the rules."]),
 dict(id="42-second-run", turns=[(U, "Keep answers under 30 words."), (A, "Okay.")] + filler(1) + [(U, "Why is grass green?"), (A, "Grass is green because of chlorophyll, a pigment that absorbs red and blue light for photosynthesis and reflects green light back to our eyes, which is why we perceive leaves and grass as green.")] + [(U, F), (A, "Grass is green because chlorophyll absorbs red and blue light and reflects green.\n\n---\n\n```text\nRules for this chat\n1. Keep every answer under 30 words.\n```")] + filler(3) + [(U, "Also, from now on use British spelling."), (A, "Will do.")] + [(U, "Why do leaves change color in fall?"), (A, "In the fall, trees stop producing chlorophyll as days get shorter and colder. The green color fades, revealing yellow and orange pigments called carotenoids that were there all along, and some trees make red anthocyanins too.")],
      final=F, block=True,
      criteria=["The corrected answer is under 30 words, uses British spelling (colour, autumn rather than fall/color), and explains why leaves change colour.",
                "The block includes both the under-30-words rule and the British spelling rule."]),
 dict(id="43-long", turns=[(U, "Two rules for this whole chat: write in the second person ('you'), and never mention brand names."), (A, "Understood.")] + filler(20, "code") + [(U, "What laptop should a student get?"), (A, "I'd recommend a MacBook Air or a Dell XPS 13. Students love them because they're light and the battery lasts all day.")],
      final=F, block=True,
      criteria=["The corrected answer gives laptop advice in the second person ('you') and mentions no brand names (no MacBook, Apple, Dell, XPS, etc.).",
                "The block includes both rules."]),
 dict(id="44-hint-lang", turns=[(U, "Réponds toujours en français et en moins de 50 mots."), (A, "D'accord.")] + filler(2) + [(U, "Quel est le plus grand océan ?"), (A, "The largest ocean is the Pacific Ocean, covering about a third of Earth's surface.")],
      final=F + " tu as oublié le français", block=True,
      criteria=["The corrected answer is in French, under 50 words, saying the Pacific is the largest ocean.",
                "The rules in the block are in French."]),
 dict(id="45-mixed-lang", turns=[(U, "Antworte bitte auf Deutsch, aber schreib Code-Kommentare immer auf Englisch."), (A, "Alles klar!")] + filler(2, "code") + [(U, "Zeig mir eine Python-Funktion, die prüft, ob eine Zahl gerade ist."), (A, "Here is a function:\n```python\ndef ist_gerade(n):\n    # Prüft, ob n gerade ist\n    return n % 2 == 0\n```")],
      final=F, block=True,
      criteria=["The corrected answer's prose is in German, with a Python even-number function whose code comments are in English.",
                "The block includes both rules (German replies, English code comments), written in German."]),
 dict(id="46-nevermind", turns=[(U, "Always start your answer with 'Great question!'"), (A, "Great question! Will do.")] + filler(2) + [(U, "Never mind the 'Great question' thing, it's annoying. Just answer directly. And use metric."), (A, "Okay.")] + filler(1) + [(U, "How far is the Moon?"), (A, "Great question! The Moon is about 238,900 miles from Earth.")],
      final=F, block=True,
      criteria=["The corrected answer does not start with 'Great question!' and gives the Moon's distance in kilometres (about 384,400 km).",
                "The block does NOT tell Claude to start with 'Great question!'. It includes the metric rule and may include 'answer directly'."]),
 dict(id="47-hint-changed", turns=[(U, "Use bullet points."), (A, "Sure.")] + filler(1) + [(U, "No wait, forget bullets entirely. Use numbered steps instead."), (A, "Okay, numbered steps.")] + filler(1) + [(U, "How do I boil an egg?"), (A, "Boiling an egg is simple. Put it in boiling water, wait about 9 minutes for hard-boiled, then cool it in cold water.")],
      final=F + " where are the bullet points?", block=True,
      criteria=["The corrected answer gives egg-boiling instructions as numbered steps (the latest rule), not bullets and not a paragraph.",
                "The block keeps the numbered-steps rule marked as changed from bullet points, and has no separate bullet-points rule."]),
 dict(id="48-summary", turns=[(U, "[This conversation was summarized. Summary of earlier messages: The user is writing a children's picture book. They asked that all text be suitable for ages 4-6, use short sentences of no more than 10 words, and avoid any scary content. They chose the main character's name: Pip the hedgehog.]"), (A, "Thanks for the summary, ready to continue.")] + filler(2) + [(U, "Write the opening line of the book."), (A, "In the dark, foreboding forest, where shadows lurked menacingly behind ancient gnarled trees, a small hedgehog named Spike trembled with fear.")],
      final=F, block=True,
      criteria=["The corrected answer is an opening line suitable for ages 4-6, with short sentence(s) of no more than 10 words, nothing scary, and the hedgehog is named Pip.",
                "The block includes the age range, short-sentence, no-scary-content rules and the Pip decision.",
                "After the block there is a line saying early messages were summarized and the user can paste a missing rule."]),
 dict(id="49-option", turns=[(U, "Give me three logo concepts for my coffee shop 'Bean There'."), (A, "1. A coffee bean shaped like a map pin.\n2. A steaming cup with a passport stamp.\n3. A minimal bean outline in a circle."), (U, "Option 2, the passport stamp. Let's develop that one only."), (A, "Great choice.")] + filler(1) + [(U, "Suggest colours for the logo."), (A, "For the map-pin bean logo, try dark brown and cream.")],
      final=F, block=True,
      criteria=["The corrected answer suggests colours for the passport-stamp cup logo (option 2), not the map-pin bean.",
                "The block records the decision: develop option 2, the passport stamp concept."]),
 dict(id="50-codeblock-rule", turns=[(U, "When you give shell commands, always put each command in its own code block and say what it does in one sentence above it. Assume I'm on Windows PowerShell."), (A, "Understood.")] + filler(2, "code") + [(U, "How do I list files and then make a new folder called test?"), (A, "Run `ls -la && mkdir test` in your terminal.")],
      final=F, block=True,
      criteria=["The corrected answer gives PowerShell commands (e.g. Get-ChildItem or dir/ls, New-Item or mkdir), each in its own code block with a one-sentence explanation above each.",
                "The block includes the one-command-per-block rule and the Windows PowerShell decision."]),
]

assert len(TESTS) == 50, len(TESTS)
assert len({t["id"] for t in TESTS}) == 50
